### ISSUE TITLE
Typo in README.md

### ISSUE THREAD

**Issue by rillig** [manolo/gwt-polymer-todo#11]
It should be `collections` instead of `collectios`, and it should point to a correct URL.

Since Markdown [does not require the reference-IDs to be numbers][mddoc], you could change them to human-readable identifiers, e.g. `[polymer]` instead of `[0]`. This prevents further confusion.

[mddoc]: https://daringfireball.net/projects/markdown/syntax#link

**Comment by manolo** [comment]
Fixed
