### ISSUE TITLE
Update GWT from 2.8.0-SNAPSHOT to 2.8.0

### ISSUE THREAD

**Issue by rillig** [manolo/gwt-polymer-todo#13]
Since 2.8.0 has been released, the SNAPSHOT version should be replaced with the released one.

At least, I couldn't build the TodoList since the SNAPSHOT version is no longer published on https://oss.sonatype.org/content/repositories/google-snapshots/com/google/gwt/gwt-user/.

**Comment by manolo** [comment]
Done
